# Generated by Django 5.0 on 2024-03-18 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_description', models.TextField(max_length=255)),
                ('project_start_date', models.DateTimeField(auto_now_add=True)),
                ('project_due_date', models.DateField(default=django.utils.timezone.now)),
                ('attachments', models.FileField(blank=True, upload_to='attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_user_id', models.IntegerField(default=1)),
                ('project_asignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
